export enum DataActionTypes {
  FETCH_DATA = "FETCH_DATA"
}

export enum FilterActionTypes {
  SELECT_ALL_AIRLINES = "SELECT_ALL_AIRLINES",
  SELECT_ALL_CLASSES = "SELECT_ALL_CLASSES",
  SELECT_ALL_STOPS = "SELECT_ALL_STOPS",
  SET_DURATION_FILTER = "SET_DURATION_FILTER",
  SET_PRICE_FILTER = "SET_PRICE_FILTER",
  TOGGLE_AIRLINE_FILTER = "TOGGLE_AIRLINE_FILTER",
  TOGGLE_CLASS_FILTER = "TOGGLE_CLASS_FILTER",
  TOGGLE_STOP_FILTER = "TOGGLE_STOP_FILTER"
}
